### ISSUE TITLE
New Feature: Support using a TOML "dotfile" config file in the user's homedir

### ISSUE THREAD

**Issue by peterdanwan** [vinhyan/barrierless#19]
As a suggestion, perhaps we can enhance your command-line tool by implementing support for a TOML "dotfile", similar to a `.gitconfig` file, which is saved to a user's home directory.

![home-directory-with-.gitconfig](https://github.com/user-attachments/assets/ef5182d0-ab07-4e3d-80a3-6dfe010aa9e0)

![TOML-styled-file](https://github.com/user-attachments/assets/b69c181f-fcea-4cee-ad71-d1d498b54af4)

Having a TOML file can enhance your users experience as they can define _default values_ for values that they'd normally have to specify on the command-line.

For example, without TOML, you might have:

```sh
bl-bot file1.txt file2.txt -l vietnamese -p gemini
```

But with the a TOML file:

```TOML
# This is the .bl-botconfig TOML file
# It stores default settings for the bl-bot command-line tool.

[defaults]
# Default language to use, for instance, if not specified via the command-line
language = "vietnamese"

# Default platform to use if not provided on the command-line
provider= "gemini"

# You can define other common options here
# For example, default file format or mode of operation
file_format = "txt"
```

You could shorten your command to something like this:

```sh
bl-bot file1.txt file2.txt
```

Since the TOML markup language is common, we can find a well-maintained TOML parser that can read through and parse your file.
